repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
  - repo: local
    hooks:
    - id: empty-label-cache
      name: Empty Label Cache
      entry: python empty_label_cache.py
      language: system